# Generated by Django 5.0.3 on 2024-03-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Foydalnuvchi telegram_ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Foydalanuvchi Username')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Foydalanuvchi first_name')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Foydalanuvchi tili')),
                ('user_tarif', models.CharField(default='Tarif mavjud', max_length=50, verbose_name='Foydalanuvchi tarifi')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Foydalanuvchi activligi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_name', models.CharField(max_length=25, verbose_name='Tariflar')),
                ('tarif_price', models.IntegerField(verbose_name='Tarif narxi')),
                ('tarif_active_date', models.DateTimeField(auto_now_add=True)),
                ('references', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
            },
        ),
    ]
