# Generated by Django 5.0.3 on 2024-04-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_ism_fam_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_tarif_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
