# Generated by Django 5.0.3 on 2024-04-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_user_active_tarif_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_tarif_user',
            new_name='active_tarif_user_end',
        ),
        migrations.AddField(
            model_name='user',
            name='active_tarif_user_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
